mod 'puppetlabs-stdlib', :latest
mod 'puppetlabs-concat', :latest
mod 'puppetlabs-apache', :latest
mod 'puppetlabs-mysql', :latest
mod 'puppet-staging', :latest
mod 'puppet-archive', :latest
mod 'puppetlabs-iis', :latest
mod 'puppetlabs-windows', :latest
mod 'puppetlabs-reboot', :latest
mod 'puppetlabs-ntp', :latest
mod 'autostructure-dod_harden_os', :latest
